<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "shopware"
 *
 * Auto generated by Extension Builder 2015-03-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Shopware Connect',
	'description' => 'Let TYPO3 get your contents (categories, products) from Shopware.',
	'category' => 'plugin',
	'author' => 'Marc Scherer',
	'author_email' => 'mail@loewenstall.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);